### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by ghost** [lxgr-linux/buildaur#2]
Special thanks to your work.
You are doing a beautiful work ;)
Good continuation

**Comment by lxgr-linux** [comment]
Thanks for wishes,
you're welcome.
I'm open for contributions ;)

**Comment by ghost** [comment]
I am sorry I can't contribute because I don't have enough time ( i am student )
I am in nutyx devel team and I have to dev an package manager for NCR ( NUTYX COMMUNITY REPOSITORY (like AUR), I need to have some advice about which language I should use for my package manager ;), if you can help me ;)  to chose.
Good continuation (sorry for my english I am french)

**Comment by ghost** [comment]
I started my project
